name: ask
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_speed_dial: ^7.0.0
  intl: ^0.19.0
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.0
  flutter_svg: ^2.0.10+1
  animated_text_kit: ^4.2.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.0
  bloc: ^8.1.4
  marquee: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    -  'assets/images/'
  fonts:
    - family: Anek Devanagari
      fonts:
        - asset: assets/fonts/AnekDevanagari_Expanded-ExtraLight.ttf